// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCew7545tsnucUh_XQxKnkJMR2PtwEc_0',
    appId: '1:952017116210:web:3eab40c92d59f22395b02b',
    messagingSenderId: '952017116210',
    projectId: 'recap-136fa',
    authDomain: 'recap-136fa.firebaseapp.com',
    storageBucket: 'recap-136fa.firebasestorage.app',
    measurementId: 'G-WJDQE6WGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpMUvC1AsQuEX1l-7GwEfES1sAPyMyteo',
    appId: '1:952017116210:android:5520bbd5cf95f49795b02b',
    messagingSenderId: '952017116210',
    projectId: 'recap-136fa',
    storageBucket: 'recap-136fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1EWUoEh6NfeyiHZeTxwaxMoZC6KI19R8',
    appId: '1:952017116210:ios:59cecea59bacc99e95b02b',
    messagingSenderId: '952017116210',
    projectId: 'recap-136fa',
    storageBucket: 'recap-136fa.firebasestorage.app',
    iosBundleId: 'com.example.recap',
  );
}
